on: [pull_request]

jobs:
    review_pr_comment:
        runs-on: ubuntu-latest
        name: comment PR
        steps:
            - name: comment
              id: comment
              uses: m31415/actions-test@v1.3
              with:
                  comment: "Hey Maik :) v1.3"
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
